version: 2

jobs:
  build:
    docker:
      - image: quay.io/rust-lang-ja/circleci:trpl1
    parallelism: 1
    steps:
      - checkout
      - run: rustc --version --verbose
      - run: cargo --version --verbose
      - run:
          name: Building 1.9 book
          command: make clean all VERSION=1.9
      - run:
          name: Building 1.6 book
          command: make clean all VERSION=1.6
      - run:
          name: Creating 1.9 artifact
          command: |
            mkdir /tmp/1.9
            cp -p docs/1.9/index.html /tmp/1.9
            cp -rp docs/1.9/book /tmp/1.9
            cp -rp docs/1.9/*.inc docs/1.9/*.css docs/1.9/*.js /tmp/1.9
            tar cJf docs-1.9.txz docs/1.9
            mv docs-1.9.txz /tmp
      - store_artifacts:
          path: /tmp/1.9
          destination: 1.9
      - store_artifacts:
          path: /tmp/docs-1.9.txz
          destination: docs-1.9.txz
      - run: rm -rf /tmp/1.9 /tmp/docs-1.9.txz
      - run:
          name: Creating 1.6 artifact
          command: |
            mkdir /tmp/1.6
            cp -p docs/1.6/index.html /tmp/1.6
            cp -rp docs/1.6/book /tmp/1.6
            cp -rp docs/1.6/*.inc docs/1.6/*.css docs/1.6/*.js /tmp/1.6
            tar cJf docs-1.6.txz docs/1.6
            mv docs-1.6.txz /tmp
      - store_artifacts:
          path: /tmp/1.6
          destination: 1.6
      - store_artifacts:
          path: /tmp/docs-1.6.txz
          destination: docs-1.6.txz
      - run: rm -rf /tmp/1.6 /tmp/docs-1.6.txz
      - deploy:
          name: If master branch, publish to GitHub Page
          command: |
            if [ "x_${CIRCLE_BRANCH}" == "x_master" ]; then
              git config user.name "bn-e (CircleCI)"
              git config user.email "bn-e@hibaridb.org"
              ./tools/circleci/push-to-master.sh
              # ./tools/circleci/trigger-trpl-pdf-ja.sh
            fi

